import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../../components'
import Container from '../../containers/container'
import { services } from "../../utils/constants";

export default function Services() {
  return (
    <Layout bgClass="bg-services bg-no-repeat bg-right-top h-full md:h-screen">
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className='flex flex-col sm:flex-row justify-between gap-10'>
          <div className='my-16'>
            <h1 className='text-4-5xl font-bold mb-2'>Our Services</h1>
            <p className='primary-text block mb-4'>
              NpowerT specializes in end - to - end services from RTL to GDS-II <br className="hidden lg:block" />by leveraging industry standard EDA tools and flows.
            </p>
            <p className='primary-text block mb-4'>
              NpowerT teams core target is to secure our customers with <br className="hidden lg:block" />lesser time to market where designs can briskly skim <br className="hidden lg:block" />through foundry-specific guidelines further avoiding <br className="hidden lg:block" />multiple iterations.
            </p>
            <p className='primary-text block mb-4'>
              npowerts core expertise is our strength in successfully <br className="hidden lg:block" />executing lower technology nodes like 3nm, 5nm, 7nm etc. Our <br className="hidden lg:block" />team of domain experts at npowert ensure to achieve the <br className="hidden lg:block" />optimistic power, performance, and area targets for a particular <br className="hidden lg:block" />design.
            </p>
          </div>
          <div className='my-2'>
            <ul>
              {services.map(service => (
                <li className='p-2 border border-hiring flex flex-1 rounded-lg bg-service-list mb-4 md:mb-2 w-full md:w-64 lg:w-80' key={service.name}>
                  <Image src={service.image} alt={service.name} className="object-contain mr-4" width={23} height={23} />
                  <p className='font-semibold'>{service.name}</p>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </Container>
    </Layout>
  )
}