import Head from 'next/head'
import Link from 'next/link'
import { Layout } from '../components'
import Container from '../containers/container'

export default function Error({ statusCode }) {
  return (
    <Layout bgClass=" h-screen">
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className='my-16 text-center'>
          <h1 className='text-4-5xl font-bold  mb-8 md:mb-12'>Error</h1>
          <div className='max-w-4xl mx-auto text-center'>
            <Link href={'/'} className="font-bold py-4 px-6 border border-black bg-learn-more text-black text-center">
              Back to Home
            </Link>
          </div>
        </div>
      </Container>
    </Layout>
  )
}