import Head from 'next/head'
import Link from 'next/link'
import Container from '../containers/container'
import { Layout } from '../components';
import Image from 'next/image';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>NPowerT : Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="flex flex-col-reverse md:flex-row justify-between">
          <div className='my-16'>
            <h1 className='text-3xl lg:text-4-5xl font-normal mb-2 leading-[48px]'>
              <span>Best</span>{` `}<br />
              <span className='font-bold'>Chiplet Design <sup>TM</sup></span><br />
              <span>in Industry</span>
            </h1>
            <p className='primary-text block my-8'>
              We design chiplet architecture with best <br className="hidden lg:block" />communication rate with our infinity fabric <br />design.
            </p>
            <div>
              <Link href={'/'} className="font-bold py-4 px-6 border border-black bg-learn-more text-black text-center md:text-left block md:inline-block ">
                Learn More
              </Link>
            </div>
          </div>
          <div className=" flex items-center justify-end">
            <Image src="/images/home-bg.png" width={550} height={550} />
          </div>
        </div>
      </Container>
    </Layout>
  )
}